algoritmo "semnome"
// Função :
// Autor :
// Data : 12/10/2018
// Seção de Declarações 
var
 numRodas: inteiro
inicio
      Escreva ("Digite o número de rodas:")
      leia (numRodas)
      
      escolha numRodas
      caso 1
      escreva ("Monociclo")
      caso 2
      escreva ("Bicicleta")
      caso 3
      escreva ("Triciclo")
      caso 4
      escreva ("Carro")
      fimescolha


fimalgoritmo
